name: Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['14', '16']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: yarn install
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build
        run: gulp

      - name: Unit Tests
        run: gulp test:unit

      - name: Browser Tests
        run: gulp test:browser
      
      - name: Integration Tests
        run: gulp test:integration
