name: Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '10.16.3'

      - name: Install Dependencies
        run: yarn install
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build
        run: gulp

      - name: Unit Tests
        run: gulp test:unit

      - name: Browser Tests
        run: gulp test:browser
      
      - name: Integration Tests
        run: gulp test:integration
